name: tiktok_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  vibrate: ^0.0.4
  video_player: any

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - left.png
    - middle.png
    - right.png
    - detail.png
    - detail2.png
    - comment.png
    - bottom.png
    - assets/Butterfly-209.mp4
    - assets/1.mp4
    - assets/2.mp4
    - assets/3.mp4
    - assets/4.mp4
    - assets/5.mp4
    - assets/6.mp4